### ISSUE TITLE
Feedback for "generator-bem-stub"

### ISSUE THREAD

**Issue by AlexanderSuvorov** [bem/generator-bem-stub#146]
Не собирается index.js. Возвращает http://localhost:8080/desktop.bundles/index/index.js 500 (Internal Server Error). Подскажите куда копнуть, чтобы javascript был. Без него мне вилы.
Если в bem-stab выбрать минификацию css, стили тоже не билдятся.

node v5.10.1
npm v3.8.6
винда восьмая
образование экономическое

**Comment by tadatuta** [comment]
В качестве «быстрофикса» стоит взять готовый репозиторий https://github.com/bem/project-stub и стартовать с него, там все гарантированно работает на маке, линуксе и на винде, если запускать под [git bash](https://git-scm.com/).

**Comment by AlexanderSuvorov** [comment]
Спасибо за быстрый ответ.

**Comment by nihil-pro** [comment]
Подскажите как запустить генератор, ругается что-то:
`fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/generator-bem-stub/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/generator-bem-stub/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-bem-stub/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)`
